name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

permissions:
  contents: read
  actions: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Create virtual environment and activate
      run: |
        py -m venv venvName
        .\venvName\Scripts\activate
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Package application as executable
      run: |
        pyinstaller --paths venvName\Lib\site-packages main.py --onefile --name SendToDiscord
    - name: Release
      if: github.event_name == 'release' && github.event.action == 'created'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/SendToDiscord.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
